spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:com/gpmall/pay/dal/persistence/*Mapper.xml"
  type-aliases-package: com.gpmall.pay.dal.entitys

ali:
  ali_service: create_direct_pay_by_user
  ali_partner:  2088122862129849
  input_charset: utf-8
  sign_type: MD5
  notify_url: https://fada6b7e.ngrok.io/pay/alipayNotify
  return_url: https://www.baidu.com
  seller_id:  2088122862129849
  seller_email:
  pay_gateway_new: https://mapi.alipay.com/gateway.do?
  it_b_pay: 1h
  private_key: g5b068b4h6kyhum33yymtdjkbqdkyj1g
  public_key: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCnxj/9qwVfgoUh/y2W89L6BkRAFljhNhgPdyPuBV64bfQNN1PjbCzkIM6qRdKBoLPXmKKMiFYnkd6rAoprih3/PrQEB/VsW8OoM8fxn67UDYuyBTqA23MML9q1+ilIZwBC2AQ2UBVOrFXfFl75p6/B5KsiNG9zpgmLCUYuLkxpLQIDAQAB
  pay_open_gateway: https://openapi.alipay.com/gateway.do
  #退款接口名
  refund_service: refund_fastpay_by_platform_pwd
  #退款通知回调地址
  refund_notify_url: https://fada6b7e.ngrok.io/refund/alipayRefundNotify

wechat:
  wechat_appid: wx632c8f211f8122c6
  wechat_mch_id: 1497984412
  wechat_appsecret: sbNCm1JnevqI36LrEaxFwcaT0hkGxFnC
  wechat_mchsecret: sbNCm1JnevqI36LrEaxFwcaT0hkGxFnC
  wechat_notifyurl: https://fada6b7e.ngrok.io/pay/wechatPayNotify
  wechat_unified_order: https://api.mch.weixin.qq.com/pay/unifiedorder
  wechat_order_query: https://api.mch.weixin.qq.com/pay/orderquery
  #申请退款url
  wechat_refund_url: https://api.mch.weixin.qq.com/secapi/pay/refund
  #退款通知回调地址
  wechat_refund_notify_url: https://fada6b7e.ngrok.io/refund/wechatRefundNotify




