spring:
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath*:com/gpmall/pay/dal/persistence/*Mapper.xml"
  type-aliases-package: com.gpmall.pay.dal.entitys

ali:
  ali_service: create_direct_pay_by_user
  ali_partner: 2088721158773470
  input_charset: utf-8
  sign_type: MD5
  notify_url: http://demo.gupaoedu.cn/pay/alipayNotify
  return_url: http://demo.gupaoedu.cn/pay/syncResult
  seller_id: 2088721158773470
  seller_email: 641437529@qq.com
  pay_gateway_new: https://mapi.alipay.com/gateway.do?
  it_b_pay: 1h
  private_key: MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCKBlUHGVcK9MrPSub88sE78Q3CNkgBxCFiSQ0bIwpATozXk/MvibFwDWnCX0Z0hqK8qxPsereZc5TZ11g3mfj6SvKzHRCRUeeSUvLJrlOA3LffKvRb5vqwx1fsZF+pic/rEfspEvuG/hLOn8TrYeKKlJn9D0GTrRv3QaqCIbPWvDW0yQS++Z42JERyf7210kKZqq9BZ602C0qqciI2JYXdXzvHbe7qzvzSWJE/g7/4bcqhrS7zI7uo1P/4XFcZD4W9PyY2unSr5CZqyXBcb8DBcmiQej7Ppf9WYi0bta6cRcfqgE9dP0Md5S+U9ja1mDzMfr3vMSWSd35F+4RaGbcTAgMBAAECggEAXPr5Cqg6Z+oSOeTWiK4sGGpB/4Q7q9zpNGHLz20iecGwxYUofOzAOKEAju1J9DPCq2CAMn1U863WJ44XIpW6ETquFpVM1OidHIh+f/jMzfFieJdiOAr49F/Fzjyr6PUquMvLK5dbFExSdRlSOdMeHocO2VgOsCIcxctZxwJXOR9aPzhsR/stw7+Kr2R2eSr7uj10A/64/DSycKl+ipawySe3xjgNaJBYgLqfp6i5j/DRLOt28C/c0R5/sRXcgqN/iWePVK9Kw2J5MBY4Hif4FSiWJPx3Sz+6/Km19ZlQGXDHkYUM2WZ+HdtOkipkVYizWme8DUgJLnxwqjtv7Hy8sQKBgQDvguLzgi4OO2gkawy9sxJmu32vFyU84AJVaRR7aK3Ta+k0aM5OnkM+fC9lev33BSyyNjSXu/vESAZbINNB6n+jxKf7zljgmnPJAJlEFPYmL3An1cZgoA+EVPk19L15ozlkS+iTbHM1kCGc0tlJKZGPSoQ+8LUpugFTti/KR0LBmQKBgQCThtxkd6vCRUj1Kqg5xa6sLekZIwZC+XaKfwijTjwKGEy4aUPO8F4pJrF1L+1GsBTr4HzgaxbL+2CQvyBOLEKNYecy30hUNG6I+GC0orht/Yn4y4bFYCUKy6pA4n4yF6dg4AOdK8E06A50BfHRkcWxsZQIej3+oDZLXbCimIEBiwKBgAriJbHu/mzDIk5VVvTfyDxG1MU6BgUoILME3VtmPE/ZHXW2NXm5E1Epj3XLCvNIlulaMTWb4yreIvvNGAxsvXQRoZh9nehG3HALyOshELZXfX8x5ZvKaioXOmPLRTjbw+Xc1SqtyOZsMDrSEfGTI/wg5LV/dpv4ycqmArHsXwoxAoGABcM+2K3UB8KtFuaTq64NJKymblTv6a3U85QCwl5L+hj45js2at74zqK0S9+TZS97obsjJaEJQu6O1xigKm2QK/WnElWmfaOOrcsF/AhfK+y7dvx8Rzl6OPG7tM0kINDLuP0HJxyOb4KhDectiwImtso4/hvIUCnx9P+z5qYOZAECgYB7egX4vUMnZSBs0d2hhfKK9P0e7paV2NET9oMy5g9Q6Y+vY+hwFcDMFmJnyZ2tyrHNOAVoZAV+LZhrXn0toINlwTvuP7vofWLnLfhVMsUVeaePAVDjgOb1EFSwMW8bOub9ywBSe65FeWHmFjTOP4PnOIuv/VVynbpOT0i9Fpo9sw==
  public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAigZVBxlXCvTKz0rm/PLBO/ENwjZIAcQhYkkNGyMKQE6M15PzL4mxcA1pwl9GdIaivKsT7Hq3mXOU2ddYN5n4+krysx0QkVHnklLyya5TgNy33yr0W+b6sMdX7GRfqYnP6xH7KRL7hv4Szp/E62HiipSZ/Q9Bk60b90GqgiGz1rw1tMkEvvmeNiREcn+9tdJCmaqvQWetNgtKqnIiNiWF3V87x23u6s780liRP4O/+G3Koa0u8yO7qNT/+FxXGQ+FvT8mNrp0q+QmaslwXG/AwXJokHo+z6X/VmItG7WunEXH6oBPXT9DHeUvlPY2tZg8zH697zElknd+RfuEWhm3EwIDAQAB
  pay_open_gateway: https://openapi.alipay.com/gateway.do
  #退款接口名
  refund_service: refund_fastpay_by_platform_pwd
  #退款通知回调地址
  refund_notify_url: http://demo.gupaoedu.cn/refund/alipayRefundNotify

wechat:
  wechat_appid: 1
  wechat_mch_id: 1
  wechat_appsecret: 1
  wechat_mchsecret: 1
  wechat_notifyurl: http://demo.gupaoedu.cn/pay/wechatPayNotify
  wechat_unified_order: https://api.mch.weixin.qq.com/pay/unifiedorder
  wechat_order_query: https://api.mch.weixin.qq.com/pay/orderquery
  #申请退款url
  wechat_refund_url: https://api.mch.weixin.qq.com/secapi/pay/refund
  #退款通知回调地址
  wechat_refund_notify_url: https://fada6b7e.ngrok.io/refund/wechatRefundNotify




