
spring:
  application:
    name: gpmall-shopping
server:
  port: 8081
dubbo:
  application:
    name: gpmall-shopping
    owner: Mic
  registry:
    address: zookeeper://192.168.13.106:2181
    check: true
    group: dubbo-dev
    simplified: true
  metadata-report:
    address: zookeeper://192.168.13.106:2181
    retry-times: 30
    cycle-report: false
    group: dubbo-dev
  scan:
    base-packages: com.gpmall.shopping
